### ISSUE TITLE
Possible InvalidStateError when receiving command

### ISSUE THREAD

**Issue by thegamecracks** [thegamecracks/berconpy#3]
This is a resurfacing of the InvalidStateError described in #2. On occasion, this error message may appear in the terminal:

```py
Traceback (most recent call last):
  File "../python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "../python3.11/asyncio/selector_events.py", line 1161, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "../python3.11/site-packages/berconpy/protocol.py", line 449, in datagram_received
    self._set_command(packet, message)
  File "../python3.11/site-packages/berconpy/protocol.py", line 241, in _set_command
    fut.set_result(message)
asyncio.exceptions.InvalidStateError: invalid state
```

This is not a fatal error (i.e. the messages following it continued to be handled correctly), but I am not sure how this could occur given how the protocol currently tries to avoid cancelling or setting the future more than once [(see source)](https://github.com/thegamecracks/berconpy/blob/de58c65851f57f933dc91abc514d676a19e7201d/src/berconpy/protocol.py#L217-L285).

## System Information

**Python version:** Python 3.11.0 (main, Nov 11 2022, 20:51:20) [GCC 8.3.0] on linux
**berconpy version:** 1.1.0

**Comment by thegamecracks** [comment]
No specific steps were taken to mitigate this error in the releases from v1.1.0 up to v2.1.0, but I have not yet noticed it occur again so this issue will be closed once more.
